export const FUN_FACTS: string[] = [
  "The average American spends $1,497 per month on non-essential items.",
  "Saving just $5 a day adds up to over $1,800 a year.",
  "The 50/30/20 rule suggests 50% needs, 30% wants, 20% savings.",
  "Credit card debt in the US exceeds $1 trillion.",
  "Emergency funds should cover 3–6 months of expenses.",
  "Automating savings makes you 2x more likely to hit your goals.",
  "The average monthly cost of subscriptions per household is $219.",
  "Paying yourself first is the #1 habit of consistent savers.",
  "44% of Americans can't cover a $400 emergency without borrowing.",
  "Buying coffee out daily costs the average person $1,100 a year.",
  "Your net worth is more important than your income.",
  "People who track spending save 20% more on average.",
  "The first $1,000 in savings is the hardest — and most important.",
  "Millennials spend more on food delivery than any other generation.",
  "Lifestyle inflation is the silent killer of wealth building.",
  "A budget isn't a restriction — it's a plan for your money.",
  "The average car payment in the US is $735/month.",
  "Renting is not wasting money — it's paying for flexibility.",
  "Index funds outperform 90% of actively managed funds over 20 years.",
  "A 1% fee on investments can cost you 28% of your final portfolio.",
  "Cash back credit cards can earn you $300–$500 a year if paid off monthly.",
  "The average person has 4.8 subscription services they forgot about.",
  "Eating out costs 5x more per meal than cooking at home on average.",
  "Net worth, not salary, is the real measure of financial health.",
  "The envelope method reduces overspending by an average of 23%.",
  "Financial stress is the #1 cause of relationship conflict.",
  "People who write down their financial goals are 42% more likely to achieve them.",
  "Even $50/month invested at 22 grows to $200,000+ by retirement.",
  "The best time to start saving was yesterday. The second best time is now.",
  "Negotiating one bill a month can save the average person $500/year.",
  "73% of Americans rank finances as their #1 source of stress.",
  "The average student loan balance is $37,000 — refinancing can save thousands.",
  "Buying generic brands saves the average household $1,500 per year.",
  "Having a no-spend day once a week saves the average person $175/month.",
  "Insurance is the most overlooked part of a financial plan.",
  "Freelance income should be saved at 30% for taxes before spending.",
  "The median retirement savings for Americans under 35 is $13,000.",
  "Paying bi-weekly on a mortgage saves years of interest payments.",
  "Unsubscribing from retail emails reduces impulse purchases by 30%.",
  "More income doesn't automatically mean more wealth — habits do.",
  "The two best days to check your finances: the 1st and 15th of the month.",
  "A $0-based budget means every dollar has a job before the month starts.",
  "High earners who don't budget are often worth less than moderate earners who do.",
  "Your credit score affects your rent, insurance rates, and even job offers.",
  "Meal prepping saves the average person $150/month in food costs.",
  "The best investment you can make in your 20s is in your own skills.",
  "Tracking spending is the financial equivalent of stepping on the scale.",
]

export function getRandomFunFact(): string {
  const seed = Math.floor(Date.now() / 10000) // changes every 10 seconds
  return FUN_FACTS[seed % FUN_FACTS.length]
}